### ISSUE TITLE
 output of code is incorrect

### ISSUE THREAD

**Issue by saurabh-saraswat21** [dbc2201/Array#1]
![output](https://user-images.githubusercontent.com/45197993/72250469-a8152480-3621-11ea-8918-2c0b71d1b512.png)

**Comment by dbc2201** [comment]
Hi @ssroyal , thank for the heads up!
I've fixed the code for now. :+1:

**Comment by dbc2201** [comment]
code changed in #2 , kindly check and close the issue.
